# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12f9f589df90cbf6348c319133e9c187150cd1df7d286c90f23cc59f92a7f6591bcd9cfdcc2895a47ba92bdf1a096039146ba988b03f6fa1c77cb32f842b766c

test:
  secret_key_base: 3ecb3deb8bcb8932d0d9d8df0a817bd494e05f72e882e975c59a537c472dc916783120d9ad39ce21702f1271abe10318b9cfe2c926c925828812abf93bffe560

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
